name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout projeto privado
        uses: actions/checkout@v4

      - name: Clonar repositório público
        run: git clone --depth=1 https://github.com/riverdata/eucatur-pricing-app-eulabs.git public-repo

      - name: Copiar arquivos (exceto o preservado)
        run: |
          rsync -av --delete \
            --exclude='.git' \
            --exclude='Jenkinsfile' \
            ./ ./public-repo/

      - name: Comitar e enviar para o público
        run: |
          cd public-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          if ! git diff --quiet --cached; then
            git commit -m "Atualização automática do projeto"
            git push https://KellySoares:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/riverdata/eucatur-pricing-app-eulabs.git main
          else
            echo "Nenhuma mudança detectada — nada para atualizar."
          fi
